### ISSUE TITLE
Figure labels/Captions

### ISSUE THREAD

**Issue by prvmalik** [msevestre/CKD-Quakification#19]
"Simulation of the pharmacokinetics of [Drug] after [a single dose of 100 mg, multiple doses of 100 mg once daily] in [healthy subjects, subject with CKD]. Observed data (circles) presented from [Study Source].

**Comment by msevestre** [comment]
ok I will use this text and replace with the correct title

**Comment by msevestre** [comment]
done. Coming in the next update
I used `subjects with CKD` instead of `subject with CKD`

**Comment by msevestre** [comment]
this is done i new report
