### ISSUE TITLE
"Section 3 Compounds" is not an .md file I can edit in the input. Should be the "results.md"

### ISSUE THREAD

**Issue by prvmalik** [msevestre/CKD-Quakification#28]

**Comment by msevestre** [comment]
@prvmalik I do not understand the problem. Are you saying that results.md should be the content of section 3 and it is not the case?

**Comment by prvmalik** [comment]
[Section3_Results_and_Discussion.md](https://github.com/msevestre/CKD-Quakification/blob/main/input/Content/Section3_Results_and_Discussion.md)

**Comment by msevestre** [comment]
maybe this one? https://github.com/msevestre/CKD-Quakification/blob/main/input/Content/Section3_Results_and_Discussion.md

**Comment by msevestre** [comment]
yep. this one. Why can't you edit it?

**Comment by prvmalik** [comment]
I can. But this is not what is in the output. Something else called "Compounds" is in the output.

**Comment by prvmalik** [comment]
I see my edits on this did not save. I will rewrite now.
